export const Feature = {
    SET_COUNT: 'SET_COUNT',
    GET_USER_DATA: 'GET_USER_DATA',
    SET_USER_DATA: 'SET_USER_DATA',
    SET_FIRST_NAME: 'SET_FIRST_NAME',
    SET_LAST_NAME: 'SET_LAST_NAME',
    SET_USER_IN_ARRAY: 'SET_USER_IN_ARRAY',
    SET_PRODUCT_LIST : 'SET_PRODUCT_LIST',
    SET_IN_ARRAY_PRODUCT_LIST : 'SET_IN_ARRAY_PRODUCT_LIST'
}